# yaml-language-server: $schema=https://raw.githubusercontent.com/buildkite/pipeline-schema/main/schema.json
steps:
  - label: "Serverless Beats Tests"
    key: "serverless-beats-integration-tests"
    retry:
      automatic:
        limit: 1
    command: |
      .buildkite/scripts/steps/beats_tests.sh
    agents:
      provider: "gcp"
      machineType: "n2-standard-8"
    plugins:
      # See https://github.com/elastic/oblt-infra/blob/main/conf/resources/repos/elastic-agent/01-gcp-oidc.tf
      # This plugin authenticates to Google Cloud using the OIDC token.
      elastic/oblt-google-auth#v1.3.0:
        lifetime: 10800 # seconds
        project-id: "elastic-observability-ci"
        project-number: "911195782929"
